# Generated by Django 6.0.7 on 2026-07-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('college', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('jdate', models.CharField(max_length=30, null=True)),
                ('total_fee', models.CharField(max_length=30, null=True)),
                ('paid_fee', models.CharField(max_length=30, null=True)),
                ('left_fee', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('technology', models.CharField(max_length=30, null=True)),
                ('image', models.FileField(max_length=30, null=True, upload_to='')),
            ],
        ),
    ]
