# Generated by Django 6.0.7 on 2026-07-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
